### ISSUE TITLE
gamedownloader resurrects snakes

### ISSUE THREAD

**Issue by hjfreyer** [TheApX/battlesnake-engine-cpp#2]
The move requests generated by gamedownloader include all the snakes that were present at the beginning of the game, even if those snakes are dead as of the requested turn. Dead snakes should be discarded.

# Repro

```
~/battlesnake-engine-cpp/build/gamedownloader/battlesnakedownloader     \
  -g 8c1b067b-51df-4564-8a89-8cc6001b30cc \
  --turn 172 --snake "experimental"
```

# Expected output

The move request should include both living snakes.

# Actual output

The move request contains 4 snakes, including `gs_fvHqRw6KrM6VM8KgV7Svt7DR` and `gs_RTPdppBqMYDFqtvkSDqCcpbB`, even though they were eliminated earlier in the game.

**Comment by TheApX** [comment]
Thanks for reporting this! It must an easy-to-fix bug, I'll take a look.
